apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: order
      port: 8081
      targetPort: 8081
  selector:
    app: order